# Generated by Django 5.2.9 on 2026-01-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("rating", models.FloatField()),
                (
                    "food_img",
                    models.ImageField(blank=True, null=True, upload_to="foodimg/"),
                ),
            ],
        ),
    ]
