# Generated by Django 5.2.9 on 2026-01-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditems",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
