# Generated by Django 5.2.9 on 2026-01-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0002_fooditems_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditems",
            name="categories",
            field=models.CharField(
                choices=[
                    ("PIZZA", "Pizza"),
                    ("BURGER", "Burger"),
                    ("FRENCH FRIES", "French Fries"),
                    ("DESSERT", "Dessart"),
                    ("BREVERAGES", "Braverages"),
                ],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
