# Generated by Django 5.2.9 on 2026-01-21 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0003_fooditems_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Basetype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basename", models.CharField(max_length=50)),
                ("base_img", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="sau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sname", models.CharField(max_length=50)),
                ("simage", models.ImageField(upload_to=None)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SizeChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size_type", models.CharField(max_length=50)),
                ("size_in_cm", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Toppings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("qty", models.IntegerField()),
                ("price", models.IntegerField()),
                ("topping_img", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="customized_options",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_type",
                    models.CharField(
                        choices=[
                            ("PIZZA", "Pizza"),
                            ("BURGER", "Burger"),
                            ("FRENCH FRIES", "French Fries"),
                            ("DESSERT", "Dessart"),
                            ("BREVERAGES", "Braverages"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "base_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basetypes",
                        to="foods.basetype",
                    ),
                ),
                (
                    "sau_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saus",
                        to="foods.sau",
                    ),
                ),
                (
                    "size_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizecharts",
                        to="foods.sizechart",
                    ),
                ),
                (
                    "toppings_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toppings",
                        to="foods.toppings",
                    ),
                ),
            ],
        ),
    ]
