# Generated by Django 5.2.9 on 2026-01-27 10:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0004_basetype_sau_sizechart_toppings_customized_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        default=uuid.uuid5, editable=False, max_length=100, unique=True
                    ),
                ),
            ],
        ),
    ]
