# Generated by Django 5.2.9 on 2026-01-27 10:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0005_order_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_details",
            name="order_id",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=100, unique=True
            ),
        ),
    ]
