# Generated by Django 5.2.9 on 2026-01-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0006_alter_order_details_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_details",
            name="totalprice",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
