# Generated by Django 5.2.9 on 2025-12-30 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.BigIntegerField()),
                ("address", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=30)),
                ("zipcode", models.ImageField(upload_to="")),
                (
                    "userpic",
                    models.ImageField(blank=True, null=True, upload_to="userimg/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
