# Generated by Django 5.2.9 on 2026-01-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learnapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="zipcode",
            field=models.CharField(max_length=50),
        ),
    ]
