# Generated by Django 5.2.9 on 2026-01-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learnapp", "0002_alter_userdetails_zipcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="user_type",
            field=models.CharField(
                choices=[("USER", "user"), ("VENDER", "vender")],
                default="user",
                verbose_name="",
            ),
        ),
    ]
